prebuilt_jar(name='hamcrest-core', binary_jar=':hamcrest-core-mvn', visibility=["PUBLIC"])
prebuilt_jar(name='junit', binary_jar=':junit-mvn', visibility=["PUBLIC"])
remote_file(name='hamcrest-core-mvn', out='hamcrest-core-1.3.jar', url='mvn:org.hamcrest:hamcrest-core:jar:1.3', sha1='42a25dc3219429f0e5d060061f71acb49bf010a0')
remote_file(name='junit-mvn', out='junit-4.11.jar', url='mvn:junit:junit:jar:4.11', sha1='4e031bb61df09069aeb2bffb4019e7a5034a4ee0')
